### ISSUE TITLE
Juno cross-chain does not work

### ISSUE THREAD

**Issue by ShenFri** [disperze/gon-wallet#2]

**Comment by giansalex** [comment]
Are you getting any error message?

**Comment by ShenFri** [comment]
Call Kepler wallet to indicate that the transaction fee is insufficient

**Comment by giansalex** [comment]
ok, try to remove Juno Testnet network in keplr, and connect to http://gon.disperze.com/ibc-transfer?chain=juno again

**Comment by ShenFri** [comment]
not ok

**Comment by TheCodeor** [comment]
same error

**Comment by giansalex** [comment]
It is fixed, it was a problem with the Juno testnet denom.

reload page, and try to add network again
